apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
   name: blob-pvc 
spec: 
   accessModes: 
      - ReadWriteOnce 
   storageClassName: ase-node-local 
resources: 
   requests: 
      storage: 30Gi
